package consoleinput

// Code generated by go-importconst DO NOT EDIT.
const FOCUS_EVENT = 16
const KEY_EVENT = 1
const MENU_EVENT = 8
const MOUSE_EVENT = 2
const WINDOW_BUFFER_SIZE_EVENT = 4
const ENABLE_WINDOW_INPUT = 8
const WAIT_ABANDONED = 128
const WAIT_OBJECT_0 = 0
const WAIT_TIMEOUT = 258
const WAIT_FAILED = -1
const ENABLE_MOUSE_INPUT = 16
